export const services = [
  {
    id: "degrade-sombreado",
    name: "Corte degrade/sombreado",
    description: "Corte com degrade e acabamento detalhado.",
    price: 35,
    duration: 40,
  },
  {
    id: "tesoura",
    name: "Corte na tesoura",
    description: "Corte completo feito na tesoura.",
    price: 35,
    duration: 40,
  },
  {
    id: "social",
    name: "Corte social",
    description: "Corte tradicional com acabamento classico.",
    price: 30,
    duration: 40,
  },
  {
    id: "raspado",
    name: "Corte raspado por igual",
    description: "Maquina uniforme com acabamento limpo.",
    price: 25,
    duration: 30,
  },
  {
    id: "pezinho",
    name: "Acabamento/pezinho",
    description: "Acerto rapido de contorno e nuca.",
    price: 5,
    duration: 15,
  },
  {
    id: "barba",
    name: "Barba",
    description: "Barba alinhada com acabamento.",
    price: 20,
    duration: 30,
  },
  {
    id: "bigode",
    name: "Bigode",
    description: "Ajuste e definicao do bigode.",
    price: 5,
    duration: 10,
  },
  {
    id: "sobrancelha",
    name: "Sobrancelha",
    description: "Design e limpeza da sobrancelha.",
    price: 5,
    duration: 5,
  },
  {
    id: "alisante",
    name: "Alisante",
    description: "Alisamento capilar.",
    price: 20,
    duration: 20,
  },
  {
    id: "botox-selagem",
    name: "Botox/selagem",
    description: "Tratamento de alinhamento e selagem.",
    price: 65,
    duration: 60,
  },
  {
    id: "pigmentacao-tinta",
    name: "Pigmentacao/tinta",
    description: "Aplicacao de pigmentacao ou tinta.",
    price: 20,
    duration: 20,
  },
  {
    id: "luzes",
    name: "Luzes",
    description: "Aplicacao de luzes no cabelo.",
    price: 60,
    duration: 60,
  },
  {
    id: "platinado-completo",
    name: "Platinado + corte + sobrancelha",
    description: "Servico completo de transformacao.",
    price: 160,
    duration: 180,
  },
];

export const gallery = [
  {
    id: 1,
    title: "Fade com detalhe",
    category: "Corte",
    image: "/fotos/corte-1.jpeg",
  },
  {
    id: 2,
    title: "Mullet moderno",
    category: "Corte",
    image: "/fotos/corte-2.jpeg",
  },
  {
    id: 3,
    title: "Social classico",
    category: "Corte",
    image: "/fotos/corte-3.jpeg",
  },
  {
    id: 4,
    title: "Degrade executivo",
    category: "Corte e barba",
    image: "/fotos/corte-4.jpeg",
  },
];
